
services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB_FILE: /run/secrets/postgres_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./datasets:/datasets
    secrets:
      - postgres_user
      - postgres_password
      - postgres_db

secrets:
   postgres_user:
     file: secrets/postgres_user.txt
   postgres_password:
     file: secrets/postgres_password.txt
   postgres_db:
     file: secrets/postgres_db.txt

volumes:
  pg_data:

