
services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./datasets:/datasets
    env_file:
      - secrets/.env.docker

volumes:
  pg_data:


